export type DocPage = { title: string; eyebrow: string; intro: string; sections: Array<{ heading: string; body: string; code?: string; language?: string; links?: Array<{ label: string; href: string }> }> };

export const docNav = [
  ["", "Overview"], ["quickstart", "Quickstart"], ["client", "Client SDK"], ["server", "Server verifier"], ["identity", "Identity semantics"], ["enrollment", "Enrollment"], ["contract", "Gate contract"], ["errors", "Errors"], ["privacy", "Privacy model"], ["threat-model", "Threat model"], ["api", "API reference"], ["examples", "Examples"],
] as const;

const install = `npm install @veilpass/sdk @veilpass/shared`;
const client = `import { VeilPass } from "@veilpass/sdk";

const veilpass = new VeilPass({
  loginOrigin: "https://login.veilpass.dev",
});

const result = await veilpass.login({ gateId: "premium-holder" });
// result never contains the wallet address`;
const server = `import { verifyVeilPassProof } from "@veilpass/server";

const verified = await verifyVeilPassProof({
  proofResult,
  expectedOrigin: "https://app.example",
  expectedGateId: "premium-holder",
  policy,
  store: durableChallengeStore,
  verifyProof: verifyNoirMembershipProof,
  requestId,
});`;

export const docs: Record<string, DocPage> = {
  "": { title: "Developer documentation", eyebrow: "VeilPass docs", intro: "Integrate origin-scoped, eligibility-gated login without receiving the user's Stellar address.", sections: [
    { heading: "What the host receives", body: "A successful login returns only eligibility, a private app ID, gate ID, epoch, normalized origin, and expiry. The host never receives the Stellar wallet address or balance. During verification, the host browser and server do receive the raw proof and public inputs, including the credential commitment, revocation hash, and one-time nullifier; treat those as sensitive request data and do not log or persist them." },
    { heading: "MVP status", body: "This repository is testnet software. The hosted login generates a local Noir/UltraHonk membership proof and the verifier checks it with the pinned verification key. The separately labeled Simulated proof endpoint is only a non-production compatibility fixture; /api/verify never accepts it." },
    { heading: "Choose the correct integration path", body: "The published browser SDK is a popup client, not a hosted authentication backend. It calls POST /api/challenges and POST /api/verify on the host application's own origin. The host developer must implement those routes, trusted origin/gate policy, durable atomic challenge and nullifier storage, a real pinned proof-verification callback, rate limits, and the application's session cookie. The @veilpass/server package supplies a verification primitive; it does not supply these adapters. Follow the quickstart and server guide before using the SDK in an application." },
    { heading: "Document set", body: "Start with Quickstart, then read Client SDK, Server verifier, API reference, Identity semantics, Enrollment, Privacy model, Threat model, Errors, and Examples. The GitHub repository README covers the project and local setup; each npm package README documents that package's exact public API and limitations." },
    { heading: "Source packages and release references", body: "Install only the public packages listed below. Their npm READMEs are part of each published tarball; source links point to the corresponding workspace directories. The contract-bindings workspace is not a published npm integration package.", links: [
      { label: "@veilpass/sdk on npm", href: "https://www.npmjs.com/package/@veilpass/sdk" },
      { label: "@veilpass/server on npm", href: "https://www.npmjs.com/package/@veilpass/server" },
      { label: "@veilpass/shared on npm", href: "https://www.npmjs.com/package/@veilpass/shared" },
      { label: "GitHub repository and implementation", href: "https://github.com/irham3/veilpass" },
      { label: "Current Testnet release status", href: "https://github.com/irham3/veilpass/blob/master/frontend/docs/evidence/delivery-status.md" },
    ] },
  ]},
  quickstart: { title: "Quickstart", eyebrow: "Start here", intro: "Create one challenge on the host, open the VeilPass login surface, verify once, then establish an opaque cookie session.", sections: [
    { heading: "Know what you are integrating", body: "This is a Testnet MVP. The client package opens the hosted login UI, but your app must provide same-origin POST /api/challenges and POST /api/verify routes. Those are required by the current 0.2.x SDK and are not configurable. Your server is responsible for trusted origin/gate selection, durable atomic replay protection, the pinned cryptographic verifier and current gate policy, abuse controls, and your application's session." },
    { heading: "Prerequisites", body: "Use a modern browser with popup and Web Crypto support; open login from a user gesture. Deploy host and login pages on exact HTTPS origins (loopback HTTP is for local development only). For real Testnet enrollment, the user also needs Freighter on Stellar Testnet and a wallet eligible under the configured gate. The default public demo checks minimum native XLM and does not need a custom asset trustline. Run env:validate in the VeilPass operator repository before deploying that service; it prints issue codes only." },
    { heading: "Install", body: "Install the browser client and shared contracts. Pin versions in your lockfile and verify package contents before production rollout.", code: install, language: "bash" },
    { heading: "Client", body: "Instantiate the SDK with your exact VeilPass login origin and call login from a button or other user gesture. A resolved result means the SDK received a successful response from your host's /api/verify route. Configure that host route to create your own server-side app session only after verification succeeds.", code: client },
    { heading: "Host server", body: "The server package validates proof policy but intentionally leaves database, chain policy, cryptographic key loading, challenge issuance, HTTP routes, request limits, and app sessions to the integrator. Do not paste an in-memory store or always-true verifier into production. Review the mandatory consume contract, route requirements, and negative tests before shipping.", code: server },
    { heading: "Before production", body: "Run valid proof, wrong-origin, wrong-gate, expired proof, stale-root/epoch, revoked credential, spent challenge, concurrent replay, body-size, rate-limit, and session-cookie tests against your own deployed host origin. Confirm your logging/tracing provider does not capture POST /api/verify bodies. A passing SDK unit test is not proof that your host's adapters are production-ready." },
  ]},
  client: { title: "Client SDK", eyebrow: "Browser boundary", intro: "The client SDK opens a dedicated login window and accepts only a response from the configured login origin and the exact popup it created.", sections: [
    { heading: "Public surface", body: "VeilPass.login accepts a gateId and optional timeout. It resolves to VerifiedLogin or throws a typed VeilPassError. It never exposes the proof payload to host application code." , code: client },
    { heading: "Channel rules", body: "The SDK uses the configured exact login origin as postMessage targetOrigin and accepts messages only from that origin, the popup window it opened, and the per-login state. It validates the payload with the strict proof schema, allows only one verification request at a time, and removes listeners on success/error, popup close, and timeout. Keep loginOrigin trusted and fixed by application configuration; never derive it from user input or the incoming message." },
    { heading: "Host routes are required", body: "The SDK sends same-origin fetches to POST /api/challenges and POST /api/verify. You must implement both on your host's origin. The SDK does not proxy these through login.veilpass.dev, and the current 0.2.x release does not provide configurable path options. See the package README for the exact responsibility boundary." },
  ]},
  server: { title: "Server verifier", eyebrow: "Trusted boundary", intro: "Bind each challenge to the trusted deployment origin and gate, then consume challenge and nullifier in one atomic operation.", sections: [
    { heading: "Verify", body: "The verifier checks the strict schema, proof timestamps, trusted expected origin, expected gate, current active policy, epoch, root, credential expiry, optional credential revocation, and the cryptographic verifier callback. It delegates challenge digest comparison, challenge expiry/binding, one-time challenge consumption, and atomic nullifier uniqueness to your ChallengeStore.consume implementation. The policy, store, verifier callback, and request ID must all be server-owned dependencies.", code: server },
    { heading: "Response minimization", body: "Return the documented success object only. Error responses contain a safe public error code and request ID, never raw verifier diagnostics." },
    { heading: "Production adapter checklist", body: "Use a durable database shared by all host instances. Lock the challenge row, verify stored digest/origin/gate/expiry, insert a unique nullifier digest, and mark the challenge spent in one transaction. Resolve active root, epoch, and revocation from trusted chain/policy state and fail closed if unavailable; implement `GatePolicy.isRevoked` when the gate supports credential-level revocation because omission means the primitive performs no per-credential revocation lookup. Pin the verification key to the exact circuit release. Add request size limits, rate limits, CSRF/origin controls, no-store responses, and a host-only session cookie with expiry no later than the proof. The library does not implement those adapters for you." },
  ]},
  identity: { title: "Identity semantics", eyebrow: "Scoped identity", intro: "privateAppId is stable for one credential, normalized origin, and gate epoch. It changes across origins.", sections: [
    { heading: "Do not reinterpret it", body: "A private app ID is not anonymous, global, permanent, or transferable. Epoch rotation, credential replacement, and policy changes can deliberately change it." },
    { heading: "Normalization", body: "Deployed origins must use HTTPS. HTTP is accepted only for loopback development. Origins are lowercase, default ports are removed, and paths, queries, fragments, user info, wildcards, and opaque origins are rejected." },
  ]},
  enrollment: { title: "Enrollment", eyebrow: "Issuer boundary", intro: "Enrollment is the one flow where the issuer observes the Stellar address and checks testnet eligibility.", sections: [
    { heading: "Before clicking", body: "Install and unlock Freighter, select Stellar Testnet, keep the same account selected for the whole flow, and make sure it holds the minimum native XLM balance displayed on the enrollment page. Read and check the disclosure box; the enrollment button remains disabled until that box is checked." },
    { heading: "1. Connect the account", body: "Select Connect Freighter and enroll. Freighter may ask you to allow VeilPass to read the active public address. Approve that request. If VeilPass was already authorized, this first prompt can be skipped automatically; the on-page progress panel still moves to the wallet and network checks." },
    { heading: "2. Approve the message", body: "After eligibility passes, Freighter opens a second approval for a readable, one-time enrollment message. Approve it without switching accounts. This is an off-chain SEP-53 message signature, not a Stellar transaction, so it does not transfer XLM or any other asset." },
    { heading: "3. Wait for local storage", body: "Keep the enrollment tab open while VeilPass issues the credential, publishes the updated gate root, and saves the credential in this browser. Completion is explicit: the progress panel says Credential stored. Only then open App A or App B for private login." },
    { heading: "If no Freighter window appears", body: "Look at the progress panel first. If it says Waiting for Freighter, open the Freighter extension from the browser toolbar, unlock it, confirm Testnet and the selected account, then return to the page. A timeout produces a recovery message and a fresh retry button; do not reuse an old challenge." },
    { heading: "Privacy and recovery", body: "The issuer sees the Stellar address and public Testnet balance during enrollment. Host apps do not receive that address. The credential stays in this browser; clearing site data or using another browser requires enrollment again. VeilPass never asks for or stores a secret key." },
  ]},
  contract: { title: "Gate contract", eyebrow: "Stellar testnet", intro: "The Soroban gate registry stores public policy configuration, credential roots, epochs, revocation state, and gate ownership. Routine login remains off-chain.", sections: [
    { heading: "Lifecycle", body: "An administrator creates a gate, updates its root at the expected epoch, rotates an epoch with a replacement root, or revokes a credential hash. Each state change emits an event. Routine login does not submit a transaction." },
    { heading: "Local commands", body: "Run contract tests and the live testnet smoke from the frontend directory. A new deployment requires a funded testnet identity and explicit contract environment values.", code: "npm run contract:test\nnpm run contract:smoke\nstellar contract build --manifest-path ../contracts/veilpass-gate/Cargo.toml --locked", language: "bash" },
  ]},
  errors: { title: "Error reference", eyebrow: "Safe failures", intro: "Public errors are stable codes. Detailed causes belong in redacted server logs keyed by requestId.", sections: [
    { heading: "Wallet and policy", body: "WALLET_NOT_FOUND means no supported wallet was detected; WRONG_NETWORK means Freighter is not using Stellar Testnet; USER_REJECTED means the person cancelled a wallet prompt; NOT_ELIGIBLE means the account does not satisfy the configured gate. Show plain guidance and let the user choose whether to retry. Do not retry a rejected wallet signature automatically." },
    { heading: "Challenge and binding", body: "CHALLENGE_EXPIRED means a short-lived challenge expired; CHALLENGE_SPENT means its one-use challenge or nullifier was consumed; ORIGIN_MISMATCH means the trusted host binding failed; GATE_MISMATCH means the active gate does not match; STALE_EPOCH means the credential is for an older gate epoch. Start a fresh login only when the underlying origin/gate/policy is correct. Never replay the old proof request." },
    { heading: "Credential and verifier", body: "CREDENTIAL_EXPIRED means proof lifetime ended; CREDENTIAL_REVOKED means the gate/credential is revoked; PROOF_INVALID means schema, root, binding, or cryptographic verification failed; SERVICE_UNAVAILABLE means a required dependency is unavailable. Retry is safe only for SERVICE_UNAVAILABLE with bounded backoff and a fresh challenge. Do not retry a revoked or invalid credential in a tight loop." },
    { heading: "Fixture and abuse control", body: "ASSET_TRUSTLINE_REQUIRED and ASSET_CLAIMED apply only to the optional issued-asset Testnet fixture. RATE_LIMITED requires backoff and should not trigger immediate retry. Local SDK lifecycle errors POPUP_BLOCKED, POPUP_CLOSED, and TIMEOUT are thrown as VeilPassError values and are not HTTP verifier codes." },
    { heading: "HTTP status and safe response", body: "Successful challenge creation returns HTTP 201. Successful verification returns HTTP 200. The example host verifier maps trusted-origin rejection to 403, expected proof/policy rejection to 400, and dependency/capacity failures to 503. Responses use stable JSON codes and an opaque requestId; never return a stack trace, SQL/chain details, proof diagnostics, wallet address, or secrets." },
  ]},
  privacy: { title: "Privacy model", eyebrow: "Exact claim", intro: "VeilPass protects the Stellar wallet address from the host dApp during the login flow.", sections: [
    { heading: "What is hidden", body: "The host verification service does not receive the Stellar wallet address or public balance, and neither host nor browser receives the user's credential secret. The host's POST /api/verify route and its request infrastructure do receive the raw proof and public inputs, including credential commitment/root, private app ID, revocation hash, one-time nullifier, challenge binding, origin, and timestamps. These values are omitted from the successful result but remain sensitive transient request data: disable body logging and trace capture and do not persist or forward them." },
    { heading: "What is not hidden", body: "The enrollment issuer sees the address. VeilPass does not hide IP address, browser fingerprint, timing, device state, or later on-chain actions. It is not a network anonymity system." },
  ]},
  "threat-model": { title: "Threat model", eyebrow: "Security model", intro: "The MVP defends against accidental wallet disclosure, cross-origin message confusion, challenge replay, nullifier reuse, and stale or revoked policy use.", sections: [
    { heading: "Trust assumptions", body: "The issuer, host verifier deployment, browser runtime, configured verifier keys, host database, and contract/policy source are trusted within their documented boundaries. The integrator must protect these components and keep policy reads fresh. Compromised endpoints, malicious extensions, traffic analysis, and endpoint malware are out of scope." },
    { heading: "Logging", body: "Prefer a request ID, a typed public error code, a coarse safe stage, and operational timing that cannot be joined to a user. Never log wallet addresses, proof bytes or request bodies, credential secrets, challenge IDs/digests/raw values, private app IDs, nullifiers, revocation hashes, cookies, or signature data. Ensure APM, reverse proxies, and error-reporting SDKs do not capture them automatically." },
  ]},
  api: { title: "API reference", eyebrow: "Host and login endpoints", intro: "Routes run on two trust boundaries in this deployment. POST /api/challenges and POST /api/verify are host-origin routes that a third-party integrator must implement. Enrollment, witness, eligibility, and health routes run on the VeilPass login service. GET /api/session is a host-side demo adapter, not an SDK requirement.", sections: [
    { heading: "Host POST /api/challenges", body: "This route belongs to the integrating host origin. Accept a strict JSON body containing gateId, derive/validate origin against trusted configuration, issue at least 32 cryptographically random bytes, bind the challenge digest, gate, exact origin and five-minute expiry durably, and return HTTP 201 with Cache-Control: no-store. Reject invalid input with a safe code; return 403 for an untrusted origin and 503 if the durable store is unavailable. The browser SDK calls this route after the popup is ready.", code: `Request\n{\"gateId\":\"premium-holder\"}\n\nChallengeResponse (201)\n{\"challengeId\":\"<uuid>\",\"challenge\":\"<base64url-random-value>\",\"origin\":\"https://app.example\",\"gateId\":\"premium-holder\",\"expiresAt\":\"<ISO-8601>\"}`, language: "json" },
    { heading: "Host POST /api/verify", body: "This route also belongs to the host. It receives the sensitive proof request, enforces strict schema and size limits, derives origin/gate policy server-side, invokes the actual verifier, and consumes challenge plus nullifier atomically. On success only, it creates the host's opaque server session. Return Cache-Control: no-store.", code: `Success: 200\n{\"ok\":true,\"eligible\":true,\"privateAppId\":\"<origin-scoped-id>\",\"gateId\":\"premium-holder\",\"epoch\":1,\"origin\":\"https://app.example\",\"expiresAt\":\"<ISO-8601>\"}\n\nFailure: 400 (or 403/503 by policy)\n{\"ok\":false,\"error\":\"PROOF_INVALID\",\"requestId\":\"<opaque-request-id>\"}`, language: "json" },
    { heading: "POST /api/verify payload", body: "The strict ProofResult carries challengeId, proof bytes, and publicInputs: gateId, epoch, origin, challengeHash, credentialCommitment, credentialRoot, privateAppId, loginNullifier, revocationHash, proofCreatedAt, and proofExpiresAt. No Stellar wallet address is part of this contract. The proof/public inputs are sensitive and must not be logged or persisted." },
    { heading: "Endpoint behavior in this repository", body: "The Next.js example route accepts at most 2,000,000 bytes for proof submission, returns HTTP 200 on success, HTTP 403 for origin mismatch, HTTP 503 for service/capacity failures, and HTTP 400 for expected invalid proof or policy failures. It emits Cache-Control: no-store. An integration may choose a different response mapping only if it preserves the strict JSON error contract, safe diagnostics, no-store behavior, and client compatibility." },
    { heading: "GET /api/session", body: "This is the example application's host-only session endpoint, not a required VeilPass SDK route. It reads a host-only vp_session cookie and returns 200 { authenticated: true, privateAppId, gateId } for a valid session; otherwise it returns 401 { authenticated: false }. Both results use Cache-Control: no-store. Production integrators should implement their own session lifecycle and CSRF policy." },
    { heading: "POST /api/credentials/witness", body: "Refreshes the signed credential's Merkle witness against the active contract root. It is part of the hosted-login service, not an endpoint a host dApp needs to call directly." },
    { heading: "Enrollment and witness routes", body: "POST /api/enrollment/challenge checks an allowed gate, resolves the exact login origin, and checks the public wallet's configured Testnet eligibility before issuing a challenge. POST /api/enrollment/issue verifies the Freighter message signature, consumes the challenge, issues a credential, updates the durable Merkle tree and publishes the new root through the gate-owner service. POST /api/credentials/witness validates the issuer signature and returns a refreshed witness for the active root. These are VeilPass issuer endpoints; host dApps must not call them as a substitute for host challenge/verify routes. Request/response bodies contain sensitive holder data and use no-store." },
    { heading: "POST /api/enrollment/eligibility", body: "Checks a public Stellar address against the configured eligibility rule on the login service. This is an enrollment preflight; it is not called by the host SDK and its result is not a login proof." },
    { heading: "GET /api/session", body: "The demo-host session endpoint returns 200 with { authenticated: true, privateAppId, gateId } or 401 with { authenticated: false }. It reads only the opaque host cookie. This route is example application behavior, not a route the SDK requires at loginOrigin." },
    { heading: "GET /api/health", body: "Returns readiness status and stable issue codes only; it must never expose configuration values or secrets. A healthy response is useful operational evidence, but it does not prove that Freighter enrollment, the live proof, or the durable tree/chain state is correct." },
    { heading: "Demo-asset fixture and proof simulation", body: "POST /api/demo-asset/challenge and POST /api/demo-asset/issue exist only for the fixed Testnet demo asset fixture and enforce wallet/origin binding and one-time claim limits. POST /api/proof/simulate is a clearly labeled non-production compatibility fixture. Production requests to simulation are rejected and /api/verify never accepts simulated proof output. Neither feature is a general faucet, payment API, or production auth path." },
    { heading: "Endpoint ownership summary", body: "On each integrating host origin: POST /api/challenges and POST /api/verify are mandatory host-owned routes; GET /api/session is optional host session behavior. On login.veilpass.dev: POST /api/enrollment/eligibility, POST /api/enrollment/challenge, POST /api/enrollment/issue, POST /api/credentials/witness, and GET /api/health; Testnet-only POST /api/demo-asset/challenge and POST /api/demo-asset/issue; non-production POST /api/proof/simulate. Never send a login-service or issuer secret to a host browser." },
  ]},
  examples: { title: "Examples", eyebrow: "Two origins", intro: "App A and App B use the same gate while receiving different private IDs for the same local credential.", sections: [
    { heading: "App A", body: "A holder-only dashboard shows standard wallet login beside VeilPass login and exposes the received payload for comparison." },
    { heading: "App B", body: "A private feedback form runs on a distinct origin and demonstrates origin separation." },
    { heading: "Integration checklist", body: "The SDK is not a turnkey backend. Before enabling a gate for users, provide concrete host-owned challenge issuance and verification routes, durable cross-instance atomic consumption, a policy adapter for current chain root/epoch/revocation, a pinned production proof callback, body/rate/origin controls, sensitive-field logging exclusions, and a session adapter. Then run positive and negative acceptance tests from the real deployed host and login origins." },
    { heading: "Repository demo versus public package", body: "The app in this repository includes its own Next.js challenge/session routes and a pinned Noir verifier. Those private app adapters are not exported by @veilpass/sdk or @veilpass/server. The npm packages are lower-level primitives; do not assume installing them provisions the database, chain configuration, routes, or the hosted login service." },
  ]},
};
