#!/usr/bin/env node
import { randomBytes } from "node:crypto";
import { existsSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

import { Keypair } from "@stellar/stellar-sdk";

export const DEFAULT_TESTNET_DEPLOYMENT = {
  hostOrigin: "http://localhost:3000",
  loginOrigin: "http://localhost:3000",
  rpcUrl: "https://soroban-testnet.stellar.org",
  contractId: "CC7FUOFBIZ7UIOG7J66QJZCWU3L2MM4GW2HZUHMSF4ZBKOGCVZ4UYJZY",
  sourceAccount: "GCUSQB6ZWO633HV7M3EF6BCWSYQMTA65RJU4OMQ435OAQ3WJRIVA43VM",
  gateId: "premium-holder",
  gateEpoch: 1,
  credentialRoot: "853beeab108a74b7fe1410d6bebb1a5bdca9ad416ebdf0cc92ab248332ad2bdc",
  assetCode: "VPT",
  minBalance: "1",
};

export function buildLocalEnvText(values) {
  return [
    "# Generated by npm run env:local. This file is ignored by git.",
    "# Public deployment boundaries (exact origins, no paths)",
    `VEILPASS_HOST_ORIGIN=${values.hostOrigin}`,
    `VEILPASS_LOGIN_ORIGIN=${values.loginOrigin}`,
    `NEXT_PUBLIC_VEILPASS_LOGIN_ORIGIN=${values.loginOrigin}`,
    "",
    "# Stellar testnet gate registry",
    "NEXT_PUBLIC_STELLAR_NETWORK=TESTNET",
    `NEXT_PUBLIC_STELLAR_RPC_URL=${values.rpcUrl}`,
    `NEXT_PUBLIC_VEILPASS_CONTRACT_ID=${values.contractId}`,
    `NEXT_PUBLIC_VEILPASS_SOURCE_ACCOUNT=${values.sourceAccount}`,
    `VEILPASS_GATE_IDS=${values.gateId}`,
    `VEILPASS_GATE_EPOCH=${values.gateEpoch}`,
    `VEILPASS_CREDENTIAL_ROOT=${values.credentialRoot}`,
    "",
    "# Testnet asset eligibility rule",
    `VEILPASS_ASSET_CODE=${values.assetCode}`,
    `VEILPASS_ASSET_ISSUER=${values.assetIssuer}`,
    `VEILPASS_MIN_BALANCE=${values.minBalance}`,
    "",
    "# Secrets: never expose with NEXT_PUBLIC_ and never commit .env.local",
    `VEILPASS_SIMULATOR_KEY=${values.simulatorKey}`,
    `VEILPASS_ISSUER_SECRET=${values.issuerSecret}`,
    `VEILPASS_FIXTURE_CREDENTIAL=${values.fixtureCredential}`,
    "",
    "# Add DATABASE_URL only for production or when testing durable replay protection.",
    "",
  ].join("\n");
}

export function buildSetupSummary({ envPath, funded, values }) {
  return [
    `Wrote ${envPath}`,
    `Contract: ${values.contractId}`,
    `Gate: ${values.gateId} epoch ${values.gateEpoch}`,
    `Credential root: ${values.credentialRoot}`,
    `Asset: ${values.assetCode}:${values.assetIssuer}`,
    `Issuer funded: ${funded ? "yes" : "skipped"}`,
    "Secrets were written only to .env.local and were not printed.",
  ].join("\n");
}

function valueAfter(args, flag, fallback) {
  const index = args.indexOf(flag);
  if (index === -1) return fallback;
  const value = args[index + 1];
  if (!value || value.startsWith("--")) throw new Error(`Missing value for ${flag}`);
  return value;
}

async function fundWithFriendbot(publicKey) {
  const response = await fetch(`https://friendbot.stellar.org?addr=${encodeURIComponent(publicKey)}`);
  if (!response.ok) throw new Error(`Friendbot returned ${response.status}`);
}

export async function runLocalEnvSetup(args = process.argv.slice(2), cwd = process.cwd()) {
  const force = args.includes("--force");
  const skipFriendbot = args.includes("--skip-friendbot");
  const envPath = path.resolve(cwd, valueAfter(args, "--env-path", ".env.local"));

  if (!force && existsSync(envPath)) {
    throw new Error(`${envPath} already exists. Re-run with --force to replace it.`);
  }

  const issuer = Keypair.random();
  const values = {
    ...DEFAULT_TESTNET_DEPLOYMENT,
    hostOrigin: valueAfter(args, "--host-origin", DEFAULT_TESTNET_DEPLOYMENT.hostOrigin),
    loginOrigin: valueAfter(args, "--login-origin", DEFAULT_TESTNET_DEPLOYMENT.loginOrigin),
    assetIssuer: issuer.publicKey(),
    simulatorKey: randomBytes(32).toString("hex"),
    issuerSecret: issuer.secret(),
    fixtureCredential: randomBytes(32).toString("hex"),
  };

  let funded = false;
  if (!skipFriendbot) {
    await fundWithFriendbot(values.assetIssuer);
    funded = true;
  }

  await writeFile(envPath, buildLocalEnvText(values), { encoding: "utf8", flag: force ? "w" : "wx", mode: 0o600 });
  return buildSetupSummary({ envPath, funded, values });
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  runLocalEnvSetup()
    .then((summary) => {
      console.log(summary);
    })
    .catch((error) => {
      console.error(error instanceof Error ? error.message : String(error));
      process.exitCode = 1;
    });
}
